# Extract collected data

## Teams and their rankings

In [1]:
from pandas import read_csv

teams = read_csv('../data/ranks/2020-06-24.csv')

History window size

In [30]:
size = 5

In [29]:
from os import listdir

collected_teams = listdir('../data/teams')

for index, row in teams.iterrows():
    name = row['name'].replace('.', '').replace('"', '') + '.csv'
    if name in collected_teams:
        team = read_csv('../data/teams/' + name)

  False       Heroic     982
1   False       Heroic     982
2    True         NOVA    1133
3    True         NOVA    1133
4   False         NOVA    1133
5   False  Team Unique    1144
6   False  Team Unique    1144
7    True  Team Unique    1144
8   False        TEMPO    1066
9   False        TEMPO    1066
10   True        TEMPO    1066
11   True        CR4ZY    1163
12  False        CR4ZY    1163
13   True        CR4ZY    1163
14   True     ViKin.gg    1286
15  False     ViKin.gg    1286
16   True     ViKin.gg    1286
17   True           B8    1004
18  False           B8    1004
19   True           B8    1004
20  False         KHAN    1087
21  False         KHAN    1087
22  False   CYBERIUM.S    1011
23  False   CYBERIUM.S    1011
24  False  FAMILY TEAM    1119
25  False  FAMILY TEAM    1119
     lost       opponent  o_rank
0    True         Fnatic    1391
1    True         Fnatic    1391
2    True         Fnatic    1391
3   False   BOOM Esports    1314
4    True   BOOM Esports    1314
5   False   BOOM Esports    1314
6    True         Fnatic    1391
7    True         Fnatic    1391
8   False   Neon Esports    1252
9   False   Neon Esports    1252
10  False   TNC Predator    1198
11  False    Team Sirius    1194
12   True   TNC Predator    1198
13  False   TNC Predator    1198
14   True    Team Sirius    1194
15  False    Team Sirius    1194
16  False    RISE Esport    1006
17   True    RISE Esport    1006
18   True   BOOM Esports    1314
19  False   BOOM Esports    1314
20  False          Ocean    1000
21  False          Ocean    1000
22  False  THE BEST TEAM    1014
23   True  THE BEST TEAM    1014
24  False     Execration     956
25  False   Neon Esports    1252
26   True         Fnatic    1391
27   True         Fnatic    1391
28   True         Fnatic    1391
29  False   BOOM Esports    1314
..    ...            ...     ...
42  False    RISE Esport    1006
43   True    RISE Esport    1006
44   True   BOOM Esports    1314
45  False   BOOM Esports    1314
46  False          Ocean    1000
47  False          Ocean    1000
48  False  THE BEST TEAM    1014
49   True  THE BEST TEAM    1014
50  False     Execration     956
51  False   Neon Esports    1252
52   True         Fnatic    1391
53   True         Fnatic    1391
54   True         Fnatic    1391
55  False   BOOM Esports    1314
56   True   BOOM Esports    1314
57  False   BOOM Esports    1314
58   True         Fnatic    1391
59   True         Fnatic    1391
60  False   Neon Esports    1252
61  False   Neon Esports    1252
62  False   TNC Predator    1198
63  False    Team Sirius    1194
64   True   TNC Predator    1198
65  False   TNC Predator    1198
66   True    Team Sirius    1194
67  False    Team Sirius    1194
68  False    RISE Esport    1006
69   True    RISE Esport    1006
70   True   BOOM Esports    1314
71  False   BOOM Esports    1314

[72 rows x 3 columns]
     lost             opponent  o_rank
0    True             EXTREMUM    1174
1   False             EXTREMUM    1174
2   False             Cyberium     978
3   False             Cyberium     978
4    True          Quincy Crew    1307
5    True          Quincy Crew    1307
6    True          Quincy Crew    1307
7   False        Evil Geniuses    1217
8    True          Quincy Crew    1307
9    True          Quincy Crew    1307
10  False  business associates    1247
11  False  business associates    1247
12  False          Quincy Crew    1307
13  False        Evil Geniuses    1217
14   True        Evil Geniuses    1217
15  False        Evil Geniuses    1217
16  False              OG.Seed    1263
17  False              OG.Seed    1263
18   True              OG.Seed    1263
19  False           beastcoast    1117
20   True           beastcoast    1117
21  False           beastcoast    1117
22  False     Thunder Predator    1228
23   True     Thunder Predator    1228
24  False     Thunder Predator    1228
25   True             ViKin.gg    1286
26  False             ViKin.gg    1286
27   True             ViKin.gg    1286
28  False          TEAM HEROIC    1060
29  False          TEAM HEROIC    1060
     lost         opponent  o_rank
0    True         Scenario    1367
1    True         Scenario    1367
2    True         Scenario    1367
3   False         Scenario    1367
4   False    ABEROMON RAFT    1085
5   False    ABEROMON RAFT    1085
6    True    ABEROMON RAFT    1085
7   False        DevilTear    1092
8   False        Butterfly    1012
9    True         Scenario    1367
10   True         Scenario    1367
11   True         Cow boys    1193
12   True       Iran Lions    1039
13  False       Iran Lions    1039
14  False  team experience    1027
15  False  team experience    1027
16  False              K4W    1017
17  False              K4W    1017
18  False           AsGhaR    1016
19  False           AsGhaR    1016
20  False        DeathWish    1064
21  False        DeathWish    1064
22  False        Deathwish     989
23  False        Deathwish     989
24  False   NEW GENERATION     984
25  False      Live Record     984
26   True         Scenario    1367
27   True         Scenario    1367
28   True         Scenario    1367
29  False         Scenario    1367
..    ...              ...     ...
42  False              K4W    1017
43  False              K4W    1017
44  False           AsGhaR    1016
45  False           AsGhaR    1016
46  False        DeathWish    1064
47  False        DeathWish    1064
48  False        Deathwish     989
49  False        Deathwish     989
50  False   NEW GENERATION     984
51  False      Live Record     984
52   True         Scenario    1367
53   True         Scenario    1367
54   True         Scenario    1367
55  False         Scenario    1367
56  False    ABEROMON RAFT    1085
57  False    ABEROMON RAFT    1085
58   True    ABEROMON RAFT    1085
59  False        DevilTear    1092
60  False        Butterfly    1012
61   True         Scenario    1367
62   True         Scenario    1367
63   True         Cow boys    1193
64   True       Iran Lions    1039
65  False       Iran Lions    1039
66  False  team experience    1027
67  False  team experience    1027
68  False              K4W    1017
69  False              K4W    1017
70  False           AsGhaR    1016
71  False           AsGhaR    1016

[72 rows x 3 columns]
Empty DataFrame
Columns: [lost, opponent, o_rank]
Index: []
Empty DataFrame
Columns: [lost, opponent, o_rank]
Index: []
Empty DataFrame
Columns: [lost, opponent, o_rank]
Index: []
Empty DataFrame
Columns: [lost, opponent, o_rank]
Index: []
Empty DataFrame
Columns: [lost, opponent, o_rank]
Index: []
Empty DataFrame
Columns: [lost, opponent, o_rank]
Index: []
     lost         opponent  o_rank
0   False      Team Meteor    1010
1   False      Team Meteor    1010
2    True      Team Meteor    1010
3   False      Team Meteor    1010
4   False      Team Meteor    1010
5   False      Team Meteor    1010
6   False    TEAM Ethereal    1038
7   False    TEAM Ethereal    1038
8    True    TEAM Ethereal    1038
9   False       Team Honor     839
10  False       Team Honor     839
11   True       Team Honor     839
12  False  Immortal Gaming    1021
13  False  Immortal Gaming    1021
14   True  Immortal Gaming    1021
15  False      Team Meteor    1010
16  False      Team Meteor    1010
17  False      Team Galaxy     998
18   True      Team Galaxy     998
19  False      Team Galaxy     998
20  False     Team Destiny    1078
21   True     Team Destiny    1078
22  False     Team Destiny    1078
23  False    Vampire Gamig    1013
24  False    Vampire Gamig    1013
25   True   Revenge Gaming    1114
26  False   Revenge Gaming    1114
27   True   Revenge Gaming    1114
28  False    TEAM Ethereal    1038
29  False    TEAM Ethereal    1038
30  False       Team Honor     839
31  False       Team Honor     839
32  False       Team Honor     839
33  False     Team Sincere     993
34  False     Team Sincere     993
35   True     Team Sincere     993
36  False    Vampire Gamig    1013
37   True    Vampire Gamig    1013
38  False    Vampire Gamig    1013
39  False       Team Brave     932
40  False       Team Brave     932
Empty DataFrame
Columns: [lost, opponent, o_rank]
Index: []
Empty DataFrame
Columns: [lost, opponent, o_rank]
Index: []
     lost        opponent  o_rank
0    True     Team Secret    1561
1    True     Team Secret    1561
2    True              OG    1304
3   False              OG    1304
4    True              OG    1304
5    True              B8    1004
6    True              B8    1004
7    True           Nigma    1429
8    True           Nigma    1429
9    True        ViKin.gg    1286
10   True        ViKin.gg    1286
11   True        EXTREMUM    1174
12   True        EXTREMUM    1174
13  False        EXTREMUM    1174
14   True       FlyToMoon    1355
15   True       FlyToMoon    1355
16  False     HellRaisers    1181
17  False     HellRaisers    1181
18  False  Winstrike Team    1104
19  False  Winstrike Team    1104
20  False            KHAN    1087
21  False            KHAN    1087
22  False  Gambit Esports    1090
23  False  Gambit Esports    1090
24  False        ViKin.gg    1286
25  False        ViKin.gg    1286
26  False        ViKin.gg    1286
27   True     Team Liquid    1345
28   True     Team Liquid    1345
29   True           Nigma    1429
30   True           Nigma    1429
31  False     Team Secret    1561
32  False     Team Secret    1561
33   True   Natus Vincere    1210
34   True   Natus Vincere    1210
35   True      Virtus.pro    1329
36  False      Virtus.pro    1329
37   True      Virtus.pro    1329
     lost         opponent  o_rank
0   False            Blaze    1083
1    True            Blaze    1083
2   False            Blaze    1083
3   False     StarLucK.Fly    1005
4    True     StarLucK.Fly    1005
5   False     StarLucK.Fly    1005
6    True      Team Sirius    1194
7   False      Team Sirius    1194
8    True      Team Sirius    1194
9    True   EHOME.Immortal    1031
10  False   EHOME.Immortal    1031
11   True   EHOME.Immortal    1031
12  False         Akatsuki     981
13  False         Akatsuki     981
14  False         Longinus     920
15  False  Team Strawberry    1098
    lost          opponent  o_rank
0   True  Thunder Predator    1228
1   True  Thunder Predator    1228
2  False      Unknown Team    1016
3  False      Unknown Team    1016
4  False           Spirits     994
Empty DataFrame
Columns: [lost, opponent, o_rank]
Index: []
     lost          opponent  o_rank
0    True             CR4ZY    1163
1    True             CR4ZY    1163
2   False          EXTREMUM    1174
3   False          EXTREMUM    1174
4    True          EXTREMUM    1174
5    True  Team Empire Hope    1299
6    True  Team Empire Hope    1299
7   False           miaww^^    1108
8    True  Team Empire Hope    1299
9   False      CyberUp Team    1005
10  False          Cyberium     978
11  False          Cyberium     978
12  False          Cyberium     978
13   True           OG.Seed    1263
14   True           OG.Seed    1263
15   True       FAMILY TEAM    1119
16   True       FAMILY TEAM    1119
17  False       FAMILY TEAM    1119
18  False       TEAM HEROIC    1060
19  False       TEAM HEROIC    1060
20   True     Nemiga Gaming    1131
21   True     Nemiga Gaming    1131
22  False  Team Empire Hope    1299
23  False  Team Empire Hope    1299
24  False  Team Empire Hope    1299
25   True  Team Empire Hope    1299
26   True  Team Empire Hope    1299
27  False              KHAN    1087
28  False              KHAN    1087
29   True              KHAN    1087
30  False         4 Zoomers    1199
31  False         4 Zoomers    1199
32  False        Team Solid    1026
33   True  SMARACIS eSports    1031
34  False  Team Empire Hope    1299
35   True  Team Empire Hope    1299
36  False  Team Empire Hope    1299
37  False           Team WP    1024
38   True           Team WP    1024
    lost                   opponent  o_rank
0  False                  Crossfire    1018
1  False                  Crossfire    1018
2   True  Australian Gaming Network    1021
3  False  Australian Gaming Network    1021
4  False                 team Moops     978
5  False                 team Moops     978
6   True              ToOnz` Reborn     975
    lost   opponent  o_rank
0   True  4 Zoomers    1199
1   True  4 Zoomers    1199
2   True    OG.Seed    1263
3   True    OG.Seed    1263
4  False  4 Zoomers    1199
5  False  4 Zoomers    1199
6  False       NOVA    1133
7  False       NOVA    1133
8   True       KHAN    1087
9   True       KHAN    1087
Empty DataFrame
Columns: [lost, opponent, o_rank]
Index: []
Empty DataFrame
Columns: [lost, opponent, o_rank]
Index: []
Empty DataFrame
Columns: [lost, opponent, o_rank]
Index: []
Empty DataFrame
Columns: [lost, opponent, o_rank]
Index: []
     lost         opponent  o_rank
0   False  Team Strawberry    1098
1    True  Team Strawberry    1098
2   False  Team Strawberry    1098
3   False     Team Veteran    1029
4   False     Team Veteran    1029
5    True     Team Veteran    1029
6    True     TNC Predator    1198
7   False     TNC Predator    1198
8   False               T1    1180
9   False               T1    1180
10  False       GoodFellaz    1052
11  False       GoodFellaz    1052
12   True           Adroit    1174
13  False           Adroit    1174
14   True     Neon Esports    1252
15  False     Neon Esports    1252
16   True     Neon Esports    1252
Empty DataFrame
Columns: [lost, opponent, o_rank]
Index: []
     lost         opponent  o_rank
0    True     Team Veteran    1029
1    True     Team Veteran    1029
2    True     Team Veteran    1029
3   False     Team Veteran    1029
4   False        Extremist    1078
5   False        Extremist    1078
6   False        Extremist    1078
7   False        Extremist    1078
8   False        Extremist    1078
9   False          EternaL     990
10  False          EternaL     990
11  False    Team pyramid      973
12  False    Team pyramid      973
13  False  Genesis Knights     989
14  False  Genesis Knights     989
15  False          WETBOIZ     952
16  False          WETBOIZ     952
Empty DataFrame
Columns: [lost, opponent, o_rank]
Index: []
    lost          opponent  o_rank
0  False  internal discord     810
Empty DataFrame
Columns: [lost, opponent, o_rank]
Index: []
     lost          opponent  o_rank
0   False          Cyberium     978
1   False        CYBERIUM.S    1011
2   False        CYBERIUM.S    1011
3   False        Team Lotus     971
4   False        Team Lotus     971
5    True           OG.Seed    1263
6    True           OG.Seed    1263
7   False         4 Zoomers    1199
8   False         4 Zoomers    1199
9   False              NOVA    1133
10  False              NOVA    1133
11   True              NOVA    1133
12   True  Team Empire Hope    1299
13   True  Team Empire Hope    1299
14   True          EXTREMUM    1174
15   True          EXTREMUM    1174
16   True       TEAM HEROIC    1060
17   True       TEAM HEROIC    1060
18   True  Team Empire Hope    1299
19  False  Team Empire Hope    1299
20   True  Team Empire Hope    1299
21  False           OG.Seed    1263
22   True           OG.Seed    1263
23  False           OG.Seed    1263
24   True          ViKin.gg    1286
25   True          ViKin.gg    1286
26  False          ViKin.gg    1286
27  False    Gambit Esports    1090
28  False    Gambit Esports    1090
29   True       Team Secret    1561
30   True       Team Secret    1561
31   True     Natus Vincere    1210
32   True     Natus Vincere    1210
33   True       Team Liquid    1345
34   True       Team Liquid    1345
    lost          opponent  o_rank
0   True           EGOBOYS    1118
1  False           EGOBOYS    1118
2   True           EGOBOYS    1118
3   True    NoPing Esports    1217
4   True    NoPing Esports    1217
5  False  Thunder Predator    1228
6   True  Thunder Predator    1228
7  False  Thunder Predator    1228
     lost             opponent  o_rank
0   False              Spirits     994
1    True              Spirits     994
2   False              Spirits     994
3    True              Spirits     994
4   False              Spirits     994
5   False                0-900    1118
6    True                0-900    1118
7   False                0-900    1118
8   False     Thunder Predator    1228
9   False     Thunder Predator    1228
10  False       Gorillaz-Pride    1080
11   True       Gorillaz-Pride    1080
12  False       Gorillaz-Pride    1080
13  False  Infinity E-sports.      999
14  False  Infinity E-sports.      999
15  False            SandBlood    1044
    lost     opponent  o_rank
0  False  Gondes ARMY     988
Empty DataFrame
Columns: [lost, opponent, o_rank]
Index: []
     lost                  opponent  o_rank
0    True                 4 Zoomers    1199
1    True                 4 Zoomers    1199
2   False             Evil Geniuses    1217
3   False             Evil Geniuses    1217
4   False  Plasma1337x VitaPLUR gum     932
5   False  Plasma1337x VitaPLUR gum     932
6    True          Thunder Predator    1228
7    True          Thunder Predator    1228
8    True               Quincy Crew    1307
9    True               Quincy Crew    1307
10   True                   PlusOne    1000
11  False                   PlusOne    1000
12   True                     CR4ZY    1163
13   True                     CR4ZY    1163
14  False                Midas Club     926
15   True                Midas Club     926
16   True       business associates    1247
17   True               Quincy Crew    1307
18  False               Quincy Crew    1307
19   True               Quincy Crew    1307
20  False          Thunder Predator    1228
21  False          Thunder Predator    1228
22   True          Thunder Predator    1228
23   True             Evil Geniuses    1217
24  False             Evil Geniuses    1217
25   True             Evil Geniuses    1217
26  False       business associates    1247
27   True       business associates    1247
28  False       business associates    1247
29   True                     CR4ZY    1163
30  False                     CR4ZY    1163
31   True                     CR4ZY    1163
     lost      opponent  o_rank
0   False      Elephant    1036
1   False      Elephant    1036
2   False        Marble    1048
3   False    Execration     956
4    True    Execration     956
5   False    Execration     956
6   False    GoodFellaz    1052
7    True    GoodFellaz    1052
8   False    GoodFellaz    1052
9   False  StarLucK.Fly    1005
10  False  StarLucK.Fly    1005
11   True  StarLucK.Fly    1005
12  False      Impunity     887
13  False      Impunity     887
14   True    Execration     956
15   True    Execration     956
    lost    opponent  o_rank
0  False  Team Cobra     860
Empty DataFrame
Columns: [lost, opponent, o_rank]
Index: []
     lost               opponent  o_rank
0    True  MOTIVADE.TRUST GAMING    1195
1   False  MOTIVADE.TRUST GAMING    1195
2    True  MOTIVADE.TRUST GAMING    1195
3   False             PG BARRACX    1065
4   False             PG BARRACX    1065
5   False               Geek Fam    1309
6    True               Geek Fam    1309
7   False               Geek Fam    1309
8    True             496 Gaming    1072
9    True             496 Gaming    1072
10  False             Execration     956
11   True             Execration     956
12  False             Execration     956
Empty DataFrame
Columns: [lost, opponent, o_rank]
Index: []
     lost            opponent  o_rank
0    True    SMARACIS eSports    1031
1   False     NatusTheBelarus    1018
2    True         Team Empire    1085
3   False            Cyberium     978
4    True            Cyberium     978
5   False            Cyberium     978
6   False            Cyberium     978
7   False            Starfall    1022
8   False  STARDUST_CRUSADERS     973
9    True                NOVA    1133
10  False            Cyberium     978
11  False            Starfall    1022
12   True    Team Empire Hope    1299
Empty DataFrame
Columns: [lost, opponent, o_rank]
Index: []

In [9]:
teams

                     name            link  rank
0                 PSG.LGD       /teams/15  1567
1             Team Secret  /teams/1838315  1561
2         INVICTUS GAMING        /teams/5  1496
3                   Nigma  /teams/7554697  1429
4                   CDEC   /teams/1520578  1392
5                  Fnatic   /teams/350190  1391
6                   EHOME        /teams/4  1376
7     Royal Never Give Up  /teams/6209804  1373
8             Vici Gaming   /teams/726228  1368
9                Scenario      /teams/166  1367
10              FlyToMoon  /teams/6953913  1355
11            Team Liquid     /teams/2163  1345
12             VP.Prodigy  /teams/7819701  1339
13             Virtus.pro  /teams/1883502  1329
14  Sparking Arrow Gaming  /teams/7407260  1316
15           BOOM Esports  /teams/7732977  1314
16               Geek Fam  /teams/3586078  1309
17            Quincy Crew  /teams/7390454  1307
18                     OG  /teams/2586976  1304
19       Team Empire Hope  /teams/6409189  1299
20             Team Aster  /teams/6209166  1297
21               Alliance   /teams/111474  1293
22               ViKin.gg  /teams/6685591  1286
23     Chicken Fighters !  /teams/7553952  1284
24               Chaos EC  /teams/7203342  1283
25        boths try again  /teams/5167450  1273
26                OG.Seed  /teams/7555613  1263
27           Neon Esports  /teams/6187657  1252
28    business associates  /teams/7681441  1247
29            Quincy Crew  /teams/7806386  1243
..                    ...             ...   ...
70        Fighting PandaS  /teams/7483893  1128
71            New Esports  /teams/8021940  1128
72            Yolo Knight  /teams/7822261  1127
73      Yangon Galacticos  /teams/7653080  1125
74           Black Knight  /teams/7443956  1124
75      Team Oracle.YOUTH  /teams/7498762  1122
76              Team Cosy  /teams/7356597  1120
77            FAMILY TEAM  /teams/7930695  1119
78                  0-900  /teams/6266565  1118
79                EGOBOYS  /teams/7893914  1118
80       Proxima E-Sports  /teams/1949879  1117
81             Dark Sided  /teams/6904952  1117
82             beastcoast  /teams/7441136  1117
83          Photon Gaming  /teams/7034601  1115
84         Revenge Gaming  /teams/7101255  1114
85           Team "ENEMY"  /teams/6350308  1113
86         Reverse Heaven  /teams/7847691  1111
87                top1sng  /teams/7153614  1109
88                miaww^^  /teams/7894580  1108
89                    XDS  /teams/5681778  1107
90           Holy Masters  /teams/7599541  1105
91           Cyber Legacy  /teams/7669103  1105
92         Sincerely Fury  /teams/7802708  1104
93         Winstrike Team  /teams/7118032  1104
94     Flash Point Gaming  /teams/7204148  1101
95           Arassa Deniz  /teams/7655250  1100
96        Team Strawberry  /teams/7485273  1098
97          eu vou estudo  /teams/7958190  1098
98                     CR  /teams/7849151  1098
99          Team Serenity  /teams/5066616  1097

[100 rows x 3 columns]